'''

Assert en Python

El uso de assert en Python nos permite realizar comprobaciones.

Si la expresión contenida dentro del mismo es False,
se lanzará una excepción, concretamente AssertionError.

assert(1==2) #False
#AssertionError

https://ellibrodepython.com/assert-python
'''


a = 4
b = 5
c = a + b
print(c) 
assert(c == 29)


